
import { Poppins } from "next/font/google";
import "./globals.css";

import Providers from "@/context/Providers";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Include necessary weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Providers>
        
          <main className="p-1 px-1 lg:px-2">
           
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
